### ISSUE TITLE
AttributeError: 'float' object has no attribute 'split'

### ISSUE THREAD

**Issue by hzeng-otterai** [timatim/ParaphraseDetection#1]
Hi, Thanks for implementing BiMPM in pytorch. I was running the script but got the following error. I am using pytorch version 0.4.0. 
```
...
Epoch: [1/20], Step: [2100/12011], Loss: 0.4734717905521393, Validation Acc:77
Epoch: [1/20], Step: [2150/12011], Loss: 0.5460430383682251, Validation Acc:73
Epoch: [1/20], Step: [2200/12011], Loss: 0.5098406672477722, Validation Acc:74
Epoch: [1/20], Step: [2250/12011], Loss: 0.47307392954826355, Validation Acc:77
Epoch: [1/20], Step: [2300/12011], Loss: 0.5216501355171204, Validation Acc:76
Epoch: [1/20], Step: [2350/12011], Loss: 0.5595301985740662, Validation Acc:75
Epoch: [1/20], Step: [2400/12011], Loss: 0.5617836713790894, Validation Acc:75
Epoch: [1/20], Step: [2450/12011], Loss: 0.5084092020988464, Validation Acc:76
Traceback (most recent call last):
  File "trainer.py", line 100, in <module>
    for i, (data, labels) in enumerate(train_loader):
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/user/ParaphraseDetection/data_loader.py", line 27, in collate_batch
    p_sentences = [b[0][0].split() for b in batch]
  File "/home/user/ParaphraseDetection/data_loader.py", line 27, in <listcomp>
    p_sentences = [b[0][0].split() for b in batch]
AttributeError: 'float' object has no attribute 'split'
```

**Comment by timatim** [comment]
What did you pass in as `p` and `q` when you initialized the `QuoraDataset` object? If you did so via the `make_dataloader`, what did you pass in as `df`? The function expects a `pandas.DataFrame` object with three columns, `p`, `q`, and `label`. Sorry this wasn't clear before, I've just updated the comment documentation in the code.

**Comment by hzeng-otterai** [comment]
Thanks! I was just using your trainer.py without any change. From the code it already has those columns `quora_train = pd.read_csv(os.path.join(args.data, 'train.tsv'), sep='\t', names=['label', 'p', 'q', 'id'])`. Probably something wrong with the data file. Let me check.
